name: Bug report
about: Report a reproducible bug
title: "fix: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for reporting this bug.
        Please provide a minimal, reproducible report.
  - type: textarea
    id: summary
    attributes:
      label: Summary
      description: What is broken?
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
      placeholder: |
        1. ...
        2. ...
        3. ...
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
    validations:
      required: true
  - type: textarea
    id: actual
    attributes:
      label: Actual behavior
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Logs / screenshots
      description: Paste error output or screenshots if available.
  - type: textarea
    id: env
    attributes:
      label: Environment
      description: OS, Rust version, and command(s) used.
    validations:
      required: true
