name: Feature request
about: Propose an improvement or new capability
title: "feat: "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Please describe the user/problem context first, then the proposed solution.
  - type: textarea
    id: problem
    attributes:
      label: Problem statement
      description: What problem are we solving?
    validations:
      required: true
  - type: textarea
    id: proposal
    attributes:
      label: Proposed solution
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives considered
  - type: textarea
    id: acceptance
    attributes:
      label: Acceptance criteria
      description: How do we know this is complete?
    validations:
      required: true
